### ISSUE TITLE
Autolayout constraints being ignored?

### ISSUE THREAD

**Issue by jstheoriginal** [keighl/KTCenterFlowLayout#14]
For some reason, when I use this framework, once I go to the tab that has the collection view, it loads already scrolled down to what appears to be close to the centre point of the collection view scrollable area.  If i just use the default Flow layout, it loads at the top of the scrollable area as expected. I believe this is due to this customized layout ignoring the constraints i've already applied.  Is this the case?

**Comment by jstheoriginal** [comment]
Well of course they were...because I put my KTCenterFlowLayout code in viewDidLayoutSubviews() function instead of viewDidLoad() :-1: 

move along...nothing to see here. :)

**Comment by AlexSplit** [comment]
@jstheoriginal Happy to hear you figured it out!
