### ISSUE TITLE
Align items to left if content size exceeds bounds

### ISSUE THREAD

**Issue by sryze** [keighl/KTCenterFlowLayout#28]
Is there any way to align items to the left side if using `.scrollDirection = UICollectionViewScrollDirectionHorizontal` when they don't fit into the collection view? Right now they centered regardless of that.

I've tried the following:

```
collectionView.contentOffset = CGPointZero;
```

But it obviously didn't work.

Also, it seems that there is an issue with horizontal scrolling: if you scroll all the way to the left it scrolls back by itself to the center, but if you do the same for the right side the scroll position sticks.

P.S. Thanks for the great library! It would take me ages to understand how to implement such a custom layout.

**Comment by keighl** [comment]
Hey @sryze, this layout doesn't support horizontal scrolling... only vertical. Should probably be on the Readme. There's popular demand for it, though. One of these days I'll take a crack at it. 

Might be a good one for you to try! It would basically be the same logic, but flipped for a different axis.
