### ISSUE TITLE
use of unresolved identifier

### ISSUE THREAD

**Issue by eraydiler** [keighl/KTCenterFlowLayout#29]
Hey, i wanted to try the library using cocapods, but xcode couldn't recognize the class somehow. Attached the screenshot for reference

My XCode Version 8.1 (8B62)
The project's code is in swift 3.0

![screen shot 2016-11-11 at 15 24 58](https://cloud.githubusercontent.com/assets/1218603/20215213/701410f6-a81b-11e6-914b-fd902960d37c.png)

**Comment by DerkBusser** [comment]
same issue here

**Comment by keighl** [comment]
Hey @eraydiler + @DerkBusser, 

Two suggestions: 

a) be sure it's in your Podfile (obviously...)

```ruby
pod 'KTCenterFlowLayout'
```

b) be sure to import the module before using it:

```swift
import UIKit
import KTCenterFlowLayout

class ViewController: UICollectionViewController {

    let centerLayout = KTCenterFlowLayout()

    // ...
}
```

Closing this for now, feel free to reopen if you have more issues.
