### ISSUE TITLE
Should account for collection view content insets. 

### ISSUE THREAD

**Issue by markst** [keighl/KTCenterFlowLayout#3]

**Comment by keighl** [comment]
@markst good call. Looks like it needs to be accounted for [here](https://github.com/keighl/KTCenterFlowLayout/blob/master/KTCenterFlowLayout.m#L46)

**Comment by keighl** [comment]
The insets are already accounted for. Because this is just a subclass of FlowLayout, the rects of each cell have already been calculated by the superclass, and take `sectionInset` into consideration.
