### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by Mazyod** [keighl/KTCenterFlowLayout#8]
Hi,

Thanks for sharing this component! I've been using it for vertical scrolling without issues, but how about supporting horizontal scrolling? Would that be something you'd be interested in?

**Comment by Mazyod** [comment]
I just realized it's trivial to support this for horizontal scrolling using content inset .. Would be great if it just worked with your code out of the box though :)

**Comment by matthewmoss** [comment]
@Mazyod How did you adapt this to work for horizontal scrolling?

**Comment by Mazyod** [comment]
@matthewmoss I didn't. I simply replaced `KTCenterFlowLayout` with `UICollectionViewFlowLayout` for horizontal scrolling, then you simply set the layout insets to:

``` swift
let cellsTotalWidth = cellsCount * (cellWidth + margin) - margin
let leftInset = min(0, (collectionView.bounds.width - cellsTotalWidth) / 2)
```

**Comment by keighl** [comment]
Hey @Mazyod @matthewmoss, one of you guys should make a layout that does it! If your use case is a simple/singular row. The layout would only need to adjust each `UICollectionViewLayoutAttributes` to have the same center as the collection view. Something like this:

``` objc
- (UICollectionViewLayoutAttributes *)layoutAttributesForItemAtIndexPath:(NSIndexPath *)indexPath
{
  UICollectionViewLayoutAttributes *attrs = [super layoutAttributesForItemAtIndexPath:indexPath];
  CGFloat centerY = self.collectionView.center.y; // adjust for content insets/...
  CGPoint center = attrs.center;
  center.y = centerY;
  attrs.center = center;
  return attrs;
}
```

To vertically items within multiple rows, it'd be more similar to this layout. Feel free to take a stab. I don't think I'll have time to flesh that out.

**Comment by alejandroivan** [comment]
As an added note, I managed to do an horizontal layout using a `UICollectionFlowLayout` and messing with the insets:

```
- (UIEdgeInsets)collectionView:(UICollectionView *)collectionView layout:(UICollectionViewLayout*)collectionViewLayout insetForSectionAtIndex:(NSInteger)section
{
    static const CGFloat cellSpacing = 2.0f;
    static const CGFloat cellWidth = 98.0f;

    if ( collectionView == self.collectionView ) { //
        NSInteger viewWidth = collectionView.bounds.size.width;
        NSInteger numberOfCells = [self collectionView:collectionView numberOfItemsInSection:0] ?: 1; // The number of cells. Ideally you would get this from a NSArray instead of this method (at least one element): NSInteger numberOfCells = self.yourData.count ?: 1;
        NSInteger totalCellWidth = cellWidth * ( numberOfCells );
        NSInteger totalSpacingWidth = cellSpacing * ( numberOfCells - 1 );

        CGFloat leftInset;
        if ( totalSpacingWidth + totalCellWidth > viewWidth ) {
            leftInset = cellSpacing;
        }
        else {
            leftInset = ( viewWidth % ( totalCellWidth + totalSpacingWidth ) ) / 2;
        }

        leftInset = MAX( 0, leftInset );
        NSInteger rightInset = leftInset;

        return UIEdgeInsetsMake(0, leftInset, 0, rightInset);
    }

    return UIEdgeInsetsZero; // Default insets for unhandled UICollectionViews
}
```

Implementing the `UICollectionViewDelegateFlowLayout` is, of course, mandatory:

`@interface YourViewController : UIViewController <UICollectionViewDelegateFlowLayout>`
